### PR TITLE
doc: fixing question 16 and 17 key names

### PR DESCRIPTION
**Pull request by OmKakatkar**
changed name, age, and power to name, power, and yuga

### CODE REVIEW

**Comment by OmKakatkar** [comment]
In the 16th and 17th question, there seems to be a mistake. I corrected the key values from "name, age, and power as Ram, 2500, Treta....." to "name, power, and yuga as Ram, 2500, Treta...."

**Comment by OmKakatkar** [comment]
Not sure if this is the right place to ask but, is it okay to directly create a pull request or should I create an issue first?

**Comment by gkanishk** [comment]
Hey @OmKakatkar usually in OSS we create an issue first before working on the solution, but here it's ok you can directly create a PR

**Comment by OmKakatkar** [comment]
Thank You @gkanishk for letting me know

**Pull request merged**
